version: "3.8"
services:
  db:
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
  app:
    depends_on:
      - db
    build:
      context: .
    ports:
      - "8080:8080"
